### ISSUE TITLE
README.md instruction #1 - error running command

### ISSUE THREAD

**Issue by ricardopesce** [scytheStudio/SCodes#12]
Hello,

First of all, congrats and thanks for sharing this useful library.
I am following the README.md instructions on how to use the submodule in a project. But in the 1st step, I got an error:

```

$ git submodule add git@gitlab.com:scythestudio/scodes.git
Cloning into '/home/rgb/QtProjects/minibrowser/scodes'...
git@gitlab.com: Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@gitlab.com:scythestudio/scodes.git' into submodule path '/home/rgb/QtProjects/minibrowser/scodes' failed
```

So I just replaced the repo location by the one here on github:
`$ git submodule add https://github.com/scytheStudio/SCodes.git`

It worked just fine.

Now, I don't know if I did something wrong or if the README file's instruction #1 must be updated.
Just trying to keep you guys informed.

Regards

**Comment by radkoder** [comment]
This is now fixed - thanks for pointing it out.
