### ISSUE TITLE
Android with Qt 6.4.3 ERror

### ISSUE THREAD

**Issue by jhay06** [scytheStudio/SCodes#29]
the example QML Barcode reader crashed 

E EGL_emulation: eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
E EGL_emulation: tid 1898: eglQueryContext(2160): error 0x3004 (EGL_BAD_ATTRIBUTE)
W libQmlBarcodeReader_x86_64.so: Qt has caught an exception thrown from an event handler. Throwing
W libQmlBarcodeReader_x86_64.so: exceptions from an event handler is not supported in Qt.
W libQmlBarcodeReader_x86_64.so: You must not let any exception whatsoever propagate through Qt code.
E libc++abi: terminating with uncaught exception of type std::out_of_range: Requested row is outside the image
F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 1871 (QThread), pid 1791 (mlbarcodereader)

**Comment by radkoder** [comment]
I'm closing this issue as for now it has the same symptom as this one: [link](https://github.com/scytheStudio/SCodes/issues/26)
Probably the same cause.
