### ISSUE TITLE
Multi-Threading: Mistake causes freeze

### ISSUE THREAD

**Issue by arBmind** [scytheStudio/SCodes#38]
https://github.com/scytheStudio/SCodes/blob/3c9c37c8d55314a429cbb7d56f68834e1bb8cccf/src/SBarcodeScanner.cpp#L76-L86

Note that `pauseProcessing()` is called on the main thread while the Worker thread is processing an image and afterwards calls `continueProcessing()`.
So I guess the library stops working because: `continueProcessing()` is called on Worker thread before the `pauseProcessing()` is called on main thread for the next camera frame.

Have fun 😥

**Comment by radkoder** [comment]
Thanks for noticing this issue.
This code is long overdue for some simplification, you can expect this will be fixed soon. 🙂
